# Generated by Django 6.1 on 2026-08-15 10:34

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="e-posta"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=20,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Kullanıcı adı 3-20 karakter olmalı, sadece harf, rakam ve alt çizgi içerebilir.",
                        regex="^[a-zA-Z0-9_]{3,20}$",
                    ),
                    accounts.models.validate_username_not_forbidden,
                ],
                verbose_name="kullanıcı adı",
            ),
        ),
    ]
